Feat/#5 docs random,filter
cau-likelion-org/kiwi-server pull request #17
Opened 2023-12-27 14:58 UTC by oro7l

## 📌 PR 내용
***
-get 'docs/random' : 임의의 CurrDoc 객체가 참조하는 HistoryDoc 객체 반환
-get 'docs/<int:generation>' : 기수별 CurrDoc이 참조하는 HistoryDoc 목록 조회

## 📝 코드 요약
***
`documents/views.py` 
- RandomDocAPI : 랜덤한 CurrDoc 객체 선택 후, 그 객체가 참조하고 있는 HistoryDoc 객체 반환
- GenerationFilteredDocAPI : path 파라미터로 받은 값(기수)에 대해 Generation 모델이 참조하는 HistoryDoc에서  CurrDoc이 참조하는 객체만 선택하고, 각 title에 대해 가장 최신의 HistoryDoc 객체를 반환

## 비고
`documents/urls.py`
이상하게 슬래쉬(/)를 마지막에 붙이면 url mapping이 안되더라구요..?

## 💌 해결 이슈
***
- Resolved : #5 

## 📸 스크린샷 (선택)
***

2023-12-27 15:21 UTC, hnnynh requested changes
위에 <str:title>/ 이 있어서 random/과 같은 형식으로 쓰면 random을 title로 인식한답니당
위의 uri를 editings/<str:title>/로 바꾸고 아래 uri를 random/ 으로 바꾸면 좋을 것 같아요

2023-12-27 15:23 UTC, hnnynh requested changes

2023-12-27 15:23 UTC, hnnynh commented on documents/urls.py
>      path('<str:title>/', DocumentEditHistoryAPI.as_view(), name='특정 문서의 전체 편집 목록'),
random이 title로 인식되는 것 같아욥

2023-12-27 15:30 UTC, oro7l commented on documents/urls.py
>      path('<str:title>/', DocumentEditHistoryAPI.as_view(), name='특정 문서의 전체 편집 목록'),
uri 바꿔도 괜찮을까요? @henseo

2023-12-27 23:41 UTC, henseo commented on documents/urls.py
>      path('<str:title>/', DocumentEditHistoryAPI.as_view(), name='특정 문서의 전체 편집 목록'),
1. documents/urls.py에서 위에서부터 순서대로 URL 매칭되니까 docs 관련 URL을 위로, history 관련 URL을 아래로 옮기기

2. config/urls.py에서 documents.urls로 진입하는 URL을 'docs/', 'history/'로 구분하지 말고 ''으로 처리한 다음 documents/urls.py에서 docs, history 관련 URL 앞에 각각 docs/, history/ 붙이기

3. history 관련 API 엔드포인트 앞에 전부 docs/ 추가해서 docs/history/~ 꼴로 바꾸기

2023-12-27 23:42 UTC, henseo commented on documents/urls.py
>      path('<str:title>/', DocumentEditHistoryAPI.as_view(), name='특정 문서의 전체 편집 목록'),
뭐가 제일 일반적인지는 모르겠지만 title이 random으로 설정될 경우는 없을 테니 셋 다 인식 문제는 해결될 것 같고, 1번이 제일 간단하고, 2, 3번은 비슷해 보입니다..!

2023-12-27 23:43 UTC, henseo commented on documents/urls.py
>      path('<str:title>/', DocumentEditHistoryAPI.as_view(), name='특정 문서의 전체 편집 목록'),
@oro7l 개인적으론 1번이 제일 깔끔할 것 같긴 한데, 저는 셋 다 괜찮아서 하나 정해주시면 그거에 맞게 코드 수정하겠습니다~

2023-12-28 04:52 UTC, oro7l commented on documents/urls.py
>      path('<str:title>/', DocumentEditHistoryAPI.as_view(), name='특정 문서의 전체 편집 목록'),
1번으로 하면 좋을 것 같습니다!!

2023-12-28 09:15 UTC, merged